"""baseline schema

Revision ID: 1f16d6419dd4
Revises: a08a444129e3
Create Date: 2025-08-31 20:37:46.624119

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mssql

# revision identifiers, used by Alembic.
revision = '1f16d6419dd4'
down_revision = 'a08a444129e3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_request_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('platform', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.create_foreign_key(None, 'service_request', ['service_request_id'], ['id'])

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('service_request_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('lead_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('cancelled_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('monthly_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('one_time_amount', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('payment_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('iban', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('recipient_full_name', sa.Unicode(length=150), nullable=True))
        batch_op.add_column(sa.Column('next_payment_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('meeting_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=120, collation='Turkish_CI_AS'),
               type_=sa.String(length=150),
               existing_nullable=False)
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30, collation='Turkish_CI_AS'),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key(None, 'service_request', ['service_request_id'], ['id'])
        batch_op.drop_column('phone')
        batch_op.drop_column('utm_source')
        batch_op.drop_column('message')
        batch_op.drop_column('email')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completed_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('completed_by', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('assigned_to', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['assigned_to'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['completed_by'], ['id'])

    with op.batch_alter_table('ticket_message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message_type', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('read_at', sa.DateTime(), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('new_email', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('old_email_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('new_email_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('email_change_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('delete_account_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('delete_account_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('password_change_token', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('password_change_expiry', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('seen_notifications', sa.Text(), nullable=True))
        batch_op.alter_column('is_super_admin',
               existing_type=mssql.BIT(),
               nullable=True,
               existing_server_default=sa.text('((0))'))
        batch_op.create_index(batch_op.f('ix_user_confirmation_token'), ['confirmation_token'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_reset_token'), ['reset_token'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_reset_token'))
        batch_op.drop_index(batch_op.f('ix_user_confirmation_token'))
        batch_op.alter_column('is_super_admin',
               existing_type=mssql.BIT(),
               nullable=False,
               existing_server_default=sa.text('((0))'))
        batch_op.drop_column('seen_notifications')
        batch_op.drop_column('password_change_expiry')
        batch_op.drop_column('password_change_token')
        batch_op.drop_column('delete_account_expiry')
        batch_op.drop_column('delete_account_token')
        batch_op.drop_column('email_change_expiry')
        batch_op.drop_column('new_email_token')
        batch_op.drop_column('old_email_token')
        batch_op.drop_column('new_email')

    with op.batch_alter_table('ticket_message', schema=None) as batch_op:
        batch_op.drop_column('read_at')
        batch_op.drop_column('message_type')

    with op.batch_alter_table('ticket', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('assigned_to')
        batch_op.drop_column('completed_by')
        batch_op.drop_column('completed_at')

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('lead', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.VARCHAR(length=120, collation='Turkish_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('message', sa.VARCHAR(collation='Turkish_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('utm_source', sa.VARCHAR(length=100, collation='Turkish_CI_AS'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('phone', sa.VARCHAR(length=30, collation='Turkish_CI_AS'), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=30, collation='Turkish_CI_AS'),
               existing_nullable=True)
        batch_op.alter_column('name',
               existing_type=sa.String(length=150),
               type_=sa.VARCHAR(length=120, collation='Turkish_CI_AS'),
               existing_nullable=False)
        batch_op.alter_column('service_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('meeting_date')
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('next_payment_date')
        batch_op.drop_column('recipient_full_name')
        batch_op.drop_column('iban')
        batch_op.drop_column('payment_method')
        batch_op.drop_column('one_time_amount')
        batch_op.drop_column('monthly_amount')
        batch_op.drop_column('completed_at')
        batch_op.drop_column('cancelled_at')
        batch_op.drop_column('lead_type')
        batch_op.drop_column('user_id')
        batch_op.drop_column('service_request_id')

    with op.batch_alter_table('Appointments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('price_amount')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('platform')
        batch_op.drop_column('meeting_link')
        batch_op.drop_column('service_request_id')

    # ### end Alembic commands ###
