"""media_user_and_uploads

Revision ID: 374aad8e34f0
Revises: 176b6e8b95b6
Create Date: 2025-08-20 15:41:45.394776

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '374aad8e34f0'
down_revision = '176b6e8b95b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
