"""appointment_meeting_payment_fields

Revision ID: 9da40e2f0901
Revises: 374aad8e34f0
Create Date: 2025-08-20 16:08:07.618596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9da40e2f0901'
down_revision = '374aad8e34f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('meeting_link', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('payment_status', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('price_amount', sa.Numeric(precision=10, scale=2), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Appointments', schema=None) as batch_op:
        batch_op.drop_column('price_amount')
        batch_op.drop_column('payment_status')
        batch_op.drop_column('meeting_link')

    # ### end Alembic commands ###
