"""add profile photo to user

Revision ID: add_profile_photo_001
Revises: a6176f9fbaac
Create Date: 2025-08-22 12:00:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_profile_photo_001'
down_revision = 'a6176f9fbaac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_photo', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_photo')
    # ### end Alembic commands ###
